# Auto‑generated by Amplitude Migrator UI. Edit via the UI, or by hand if needed.

SOURCE_PROJECT_API_KEY = '117b40ccd84e3772196019420f7323f1'
SOURCE_REGION = 'US'
LOCAL_EXPORT_GZ_PATH = '/Users/yonatanhadadtoko/Documents/GitHub/ai-patient-summary-Final/backend/exports/unpacked/727121/727121_2025-08-17_7#0.json.gz'
EXPORT_START = ''
EXPORT_END = ''
DEST_PROJECT_API_KEY = '7a62c686d3c2cee9b0dae727842b7f5d'
DEST_REGION = 'US'
EVENT_ALLOWLIST = ['visit_submitted']
EVENT_PROPERTY_KEEP = {'visit_submitted': ['doctorName']}
EVENT_RENAME_MAP = {}
EVENT_PROP_RENAME_MAP = {'visit_submitted': {'doctorName': 'doctor'}}
USER_ID_REMAP_PATH = '/Users/yonatanhadadtoko/Documents/GitHub/ai-patient-summary-Final/amplitude_migration_project/device_id_remap.csv'
REMAP_SCOPE = 'device_id'
TIME_STRATEGY = 'prefer_client_fallback_server_received'
ORIGINAL_TIMES_AS_PROPERTIES = False
DRY_RUN = False
REPORTS_DIR = '/Users/yonatanhadadtoko/Documents/GitHub/ai-patient-summary-Final/amplitude_migration_project/migration_runs'
REPORT_SAMPLE_LIMIT = 5
VERBOSE = True
